apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthchecker
  labels:
    app: healthchecker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthchecker
  template:
    metadata:
      labels:
        app: healthchecker
    spec:
      containers:
      - name: healthchecker
        image: us-central1-docker.pkg.dev/irio-402819/mimuw-labs/healthchecker:v2
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: google-cloud-keys
          mountPath: /var/secrets/google
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/application_default_credentials.json
      volumes:
      - name: google-cloud-keys
        secret:
          secretName: google-cloud-keys